---
apiVersion: v1
kind: Service
metadata:
  name: jpa-dataloader
  labels:
    app: jpa-dataloader
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: jpa-dataloader
    tier: compute
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jpa-dataloader
  labels:
    app: jpa-dataloader
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jpa-dataloader
        tier: compute
    spec:
      containers:
        - image: fmrtl73/jpa-dataloader:latest
          imagePullPolicy: Always
          name: jpa-dataloader
          env:
            - name: spring_profiles_active
              value: prod
            - name: spring_datasource_url
              value: jdbc:postgresql://px-patroni/people
            - name: spring_datasource_username
              value: postgres
            - name: dataloader_numberofrecords
              value: '1000000'

          ports:
            - containerPort: 8080
