---
apiVersion: v1
kind: Service
metadata:
  name: jpa-rest-api
  labels:
    app: px-jpa-rest
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: jpa-rest-api
    tier: compute
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jpa-rest-api
  labels:
    app: px-jpa-rest
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jpa-rest-api
        tier: compute
    spec:
      containers:
        - image: fmrtl73/px-jpa-rest:latest
          imagePullPolicy: Always
          name: jpa-rest-api
          env:
            - name: spring_profiles_active
              value: prod
            - name: spring_datasource_url
              value: jdbc:postgresql://px-patroni.default.svc.cluster.local/people
            - name: spring_datasource_username
              value: postgres
            - name: spring_datasource_password
              value: tea
          ports:
            - containerPort: 8080
